version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application...
      - mkdir -p deploy
      - cp -r * deploy
  post_build:
    commands:
      - echo Zipping the deployment files...
      - zip -r deploy.zip deploy

artifacts:
  files:
    - deploy.zip